### ISSUE TITLE
API ReportScore: Request sent too early

### ISSUE THREAD

**Issue by ghost** [MarshalX/SalienSnake#2]
Noticed a potential API issue:
"Request sent too early" Might be an api rate-limiting issue.

![capture](https://user-images.githubusercontent.com/38169527/41798709-eaf803ec-762b-11e8-8711-4e55aa7a5aca.PNG)

**Comment by MarshalX** [comment]
Interesting idea. I will check it tomorrow. However, please note that this warning is also caused by the operation of two accounts. Can there be such a small rate-limit?

**Comment by MarshalX** [comment]
Can you upgrade to the latest version and run again? What warning messages do you see? I do not have as many accounts to check. Thank you!

**Comment by n1ghtshade** [comment]
Just updated! 
![capture](https://user-images.githubusercontent.com/38169527/41814651-15e16ff4-7711-11e8-9484-eb3d1308369d.PNG)

**Comment by ghost** [comment]
Just managed to update. looks like the issue is still occuring:
![capture](https://user-images.githubusercontent.com/38169527/41814671-e2e43ce8-7711-11e8-9116-f7d9c17af689.PNG)

**Comment by MarshalX** [comment]
Between requests there is a delay... The first request is also with a warning... Do you have the same problem when using other scripts?

**Comment by MarshalX** [comment]
One more try with new version? 😊 The first warning can still be given. Let the bot work for ~ten minutes.

**Comment by MarshalX** [comment]
Added a flood mode for sending a report with score. I do not know how this will respond to Steam..
