### ISSUE TITLE
API. ReportScore. Did not have time to send the report or did not attack the zone.  

### ISSUE THREAD

**Issue by sbenrap** [MarshalX/SalienSnake#3]
Happening in Planet 17, more often than I would like :(
I really like the idea of a python script - any idea what is causing it?

**Comment by MarshalX** [comment]
How many accounts are running? Can you send a log with debugging enabled (-d arg). Do not forget to remove the token from the logs.

**Comment by MarshalX** [comment]
I think this is a Steam problem. They do not know when to send 😂. The bot supports the delay between sending the report how other bots (01:50-02:00).

Even the official game at the end of the capture throws an error
```
if ( eResult == 27 )
{
	instance.m_bJoiningPlanet = false;
	ZoneCaptured();
	gGame.ChangeState( new CBattleSelectionState( instance.m_PlanetData.id ) );
}
else
{
	instance.m_bJoiningPlanet = false;
	GameLoadError();
}
```
```
function GameLoadError()
{
	ShowAlertDialog( 'Game Error', 'There was an error loading required game content.  Your game will be restarted.' )
		.done( function() {  window.location.reload(); } );
}
```
Familiar message? It often popped up when I was playing through the browser.

As a solution, I can try not to become attached to the time of sending the report, but this will cause a large number of requests to the server of the Steam...

**Comment by MarshalX** [comment]
Added a flood mode for sending a report with score. I do not know how this will respond to Steam..

**Comment by sbenrap** [comment]
Thanks for the response, I will test the new version!

**Comment by sbenrap** [comment]
I tested the new version and with that I just get an endless stream of the original message (about ~1 or 2 per second)
WARNING [00:44:26] Account #0: API. ReportScore. Did not have time to send the report or did not attack the zone.    

Went back to the original version I downloaded for now (since that seems to be more stable).

Thanks again.

**Comment by MarshalX** [comment]
https://github.com/MarshalX/SalienSnake/commit/50778ea7c8fe45698a2d45fa52ef5731e12d2290

> I just get an endless stream of the original message

I fixed this issue in the latest version

**Comment by sbenrap** [comment]
Thanks, latest version seems to be working great!
Also - apologies for delayed responses, bit of a stressful time at the moment so I'm not around the computer much
