### ISSUE TITLE
API. ReportScore. X-eresult: 27; x-error_message: None

### ISSUE THREAD

**Issue by Franinc** [MarshalX/SalienSnake#4]
3 accounts.

Debug log:
[nohup.txt](https://github.com/MarshalX/SalienSnake/files/2132026/nohup.txt)

**Comment by MarshalX** [comment]
There is one error, the description of which can be obtained from the game code. Hooray!

```
if ( eResult == 27 )
{
    instance.m_bJoiningPlanet = false;
    ZoneCaptured();
    gGame.ChangeState( new CBattleSelectionState( instance.m_PlanetData.id ) );
}
```
[Source code (1061 line)](https://steamcommunity-a.akamaihd.net/public/javascript/saliengame/game.js?l=english)

```
function ZoneCaptured()
{
	ShowAlertDialog( 'Zone Captured', 'This zone has been recaptured from the Duldrumz by the Steam Community.<br>Help capture another tile and represent your favorite group to help them claim territory by clicking the flag on your Salien\'s ship!' );
}
```
[Source code (91 line)](https://steamcommunity-a.akamaihd.net/public/javascript/saliengame/gamehelpers.js?l=english)

In my opinion, you just did not have time to go again to the zone. The bot goes to the zones if the capture progress is less than 95 percent. Is it possible that in 2(~01:50) minutes all the bots and players scored 5 percent?

Although, judging by the logs, the progress of capture was 72 percent ...

**Comment by MarshalX** [comment]
In any case, this is a server side error, not a bot. The next update will output a description of this error. Thanks!

**Comment by MarshalX** [comment]
In any case, this is a server side error, not a bot. The next update will output a description of this error. Thanks!
