### ISSUE TITLE
When a zone is finished script becomes stuck in a loop

### ISSUE THREAD

**Issue by sbenrap** [MarshalX/SalienSnake#5]
Looks like the script gets stuck in a loop when a zone completes:

WARNING [23:27:38] Account #0: I can't attack this zone. It's captured!                                                                                                                                            
INFO  [23:27:38] Commander: I check the accuracy of my information on zone 9                                                                                                                                       
INFO  [23:27:38] Information has become wrong! I give new data...                                                                                                                                                  
INFO  [23:27:39] Commander: can't get planets with the complexity level of zones Difficulty.HIGH                                                                                                                   
WARNING [23:27:40] Account #0: I can't attack this zone. It's captured!                                                                                                                                            
INFO  [23:27:40] Commander: I check the accuracy of my information on zone 9                                                                                                                                       
INFO  [23:27:40] Information has become wrong! I give new data...                                                                                                                                                  
INFO  [23:27:42] Commander: can't get planets with the complexity level of zones Difficulty.HIGH                                                                                                                   
WARNING [23:27:42] Account #0: I can't attack this zone. It's captured!                                                                                                                                            
INFO  [23:27:42] Commander: I check the accuracy of my information on zone 9

**Comment by MarshalX** [comment]
I know about this problem and try to fix it. After a while, it will not disappear?

**Comment by sbenrap** [comment]
I waited for about 2 minutes before restarting the script - how long should I try next time?

**Comment by MarshalX** [comment]
No more than five minutes... Now I'm trying to get the same problem as you. So far, no luck.
![screen](https://user-images.githubusercontent.com/15520314/41938070-b53dab54-799a-11e8-89fe-3a54dd2df769.png)

**Comment by sbenrap** [comment]
I think it only happens if a zone is finished, Planet 22 Zone 10 is currently at 70%, probably around 30 minutes to complete. If I hit the issue I will wait 5 minutes and report back to say whether it eventually got unstuck or not.

Thanks!

**Comment by MarshalX** [comment]
Confirm. I have the same thoughts. In my opinion, the Steam API does not immediately update the flag "captured" of the zone.

```
2018-06-26T20:18:00.705704+00:00 app[worker.1]: INFO  [20:18:00] Account #1: Attacking zone 0; Difficulty.MEDIUM
--
  | 2018-06-26T20:19:56.852962+00:00 app[worker.1]: INFO  [20:19:56] Account #0: Current score = 2632200/3600000; Current level = 11
  | 2018-06-26T20:19:57.128146+00:00 app[worker.1]: WARNING [20:19:57] Account #0: I can't attack this zone. It's captured! (140598404450048)
  | 2018-06-26T20:19:57.128290+00:00 app[worker.1]: INFO  [20:19:57] Commander: I check the accuracy of my information on zone 0 (140598404450048)
  | 2018-06-26T20:19:57.265942+00:00 app[worker.1]: INFO  [20:19:57] Information has become wrong! I give new data... (140598404450048)
  | 2018-06-26T20:19:58.147988+00:00 app[worker.1]: INFO  [20:19:58] Commander: can't get planets with the complexity level of zones Difficulty.HIGH
  | 2018-06-26T20:19:58.408696+00:00 app[worker.1]: WARNING [20:19:58] Account #0: I can't attack this zone. It's captured! (140598404450048)
  | 2018-06-26T20:19:58.408797+00:00 app[worker.1]: INFO  [20:19:58] Commander: I check the accuracy of my information on zone 0 (140598404450048)
  | 2018-06-26T20:19:58.474483+00:00 app[worker.1]: INFO  [20:19:58] Information has become wrong! I give new data... (140598404450048)
```
```

2018-06-26T20:21:01.393167+00:00 app[worker.1]: WARNING [20:21:01] Account #2: I can't attack this zone. It's captured! (140598287787776)
--
  | 2018-06-26T20:21:01.525074+00:00 app[worker.1]: INFO  [20:21:01] Commander: can't get planets with the complexity level of zones Difficulty.HIGH
  | 2018-06-26T20:21:01.530823+00:00 app[worker.1]: INFO  [20:21:01] Commander: All attack the planet 22, zone 9 (96%)!
  | 2018-06-26T20:21:01.805876+00:00 app[worker.1]: INFO  [20:21:01] Commander: can't get planets with the complexity level of zones Difficulty.HIGH
  | 2018-06-26T20:21:01.809847+00:00 app[worker.1]: INFO  [20:21:01] Commander: I check the accuracy of my information on zone 0 (140598304569088)
  | 2018-06-26T20:21:01.878238+00:00 app[worker.1]: INFO  [20:21:01] Information has become wrong! I give new data... (140598304569088)
  | 2018-06-26T20:21:02.329443+00:00 app[worker.1]: INFO  [20:21:02] Commander: can't get planets with the complexity level of zones Difficulty.HIGH
  | 2018-06-26T20:21:02.331919+00:00 app[worker.1]: INFO  [20:21:02] Commander: I check the accuracy of my information on zone 0 (140598287787776)
  | 2018-06-26T20:21:02.369500+00:00 app[worker.1]: INFO  [20:21:02] Account #0: Attacking zone 9; Difficulty.MEDIUM
  | 2018-06-26T20:21:02.398207+00:00 app[worker.1]: INFO  [20:21:02] Information has become wrong! I give new data... (140598287787776)
  | 2018-06-26T20:21:02.815657+00:00 app[worker.1]: INFO  [20:21:02] Commander: can't get planets with the complexity level of zones Difficulty.HIGH
  | 2018-06-26T20:21:03.258726+00:00 app[worker.1]: INFO  [20:21:03] Account #2: Attacking zone 9; Difficulty.MEDIUM
  | 2018-06-26T20:21:03.276458+00:00 app[worker.1]: INFO  [20:21:03] Account #1: Attacking zone 9; Difficulty.MEDIUM

```
The flag "captured" appeared after ~ 1 minute

**Comment by MarshalX** [comment]
I'm waiting for the capture of the tenth zone (97%). If our guesses are correct, then I issue a fix

**Comment by MarshalX** [comment]
```
"captured": false,
"capture_progress": 0.997995853424072266,

"captured": true,
"capture_progress": 1,
```

The value changed instantly, but the error was. The work was restored...
