### ISSUE TITLE
Script's crash

### ISSUE THREAD

**Issue by unmd101** [MarshalX/SalienSnake#7]
Hi,just want to let you know about this issue.It's happens when script is working 5 minutes or more.
[log.txt](https://github.com/MarshalX/SalienSnake/files/2152929/log.txt)

**Comment by MarshalX** [comment]
This is a problem clearly on your side, not on the bot side. Are you sure that the python is functioning correctly?

**Comment by unmd101** [comment]
I think so, I'm using 3.6.5 version.
Besides, I'm running another py script in the same time maybe it's causes this problem.

**Comment by MarshalX** [comment]
Does the bot really work for a while correctly?

**Comment by unmd101** [comment]
I'm not sure, he spamming this before the crash:
`Account #0: I can not leave the planet, I'm in the zone`
`Trying to leave the current Instance.planet(#42)`

**Comment by MarshalX** [comment]
If he gets stuck on this, then this can not be called correct work. There is no error or exception in your logs... However, try reinstalling the python and requests.

The bot has been well successfully tested on various system. Windows, various linux distributions... Unmistakably works on heroku.
