### ISSUE TITLE
Error once level 25

### ISSUE THREAD

**Issue by drakierd** [MarshalX/SalienSnake#8]
After achieving level 25, it seems that it can not go any further. Output from console is this:

```
INFO  [19:50:52] Commander: I get the optimal planet and landing zone!
INFO  [19:50:54] Commander: can't get planets with the type of zones Type.boss
INFO  [19:50:54] Commander: All attack the planet 530, zone 27 (86%)!
INFO  [19:50:55] Thread 'Account #0' has started!
Exception in thread Account #0:
Traceback (most recent call last):
  File "/usr/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "SalienSnake.py", line 398, in run
    self.player['response']['next_level_score'],
KeyError: 'next_level_score'
```

Looks like the problem is that when you reach "max level" there is no `next_level_score` ... While I'm now maxed and don't care about leveling up anymore, it would be nice to get some exposure on planets to get entered into the drawings.

Also.. THANK YOU for making this. It was really helpful. Спасибо большое. 🙏 👍

**Comment by MarshalX** [comment]
> Also.. THANK YOU for making this. It was really helpful. Спасибо большое. 🙏 👍

You are welcome 😉
